CREATE TABLE USER (
    id bigint NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    gender varchar(10) NOT NULL,
    birth DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(email)
)