CREATE TABLE DIET (
    id bigint NOT NULL PRIMARY KEY AUTO_INCREMENT,
    start DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finish DATETIME DEFAULT CURRENT_TIMESTAMP,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP,
    user_id bigint NOT NULL,

    FOREIGN KEY (user_id)
        REFERENCES USER(id)
)